# NOTE: The "pagename" value must start with an uppercase "B" and should be followed by the year (YY) and WMDE.
# Example: "B18WMDE_"
# See https://github.com/wmde/fundraising-infrastructure/wiki/How-to-manage-banners-on-de.wikipedia.org

# A Campaign with global settings
[desktop]
name = "Desktop"
icon = "desktop"
campaign = "WMDE_FR_2025_Desktop_DE_11"
description = "Based on VAR of desktop-de-10, VAR: has new mustard colored theme/design with overlapping submit button"
campaign_tracking = "11-ba-251118"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype&vectornightmode=1"
preview_link_offline = ""
preview_url = 'https://de.wikipedia.org/wiki/Hamster?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_DE"

# Banners of the campaign, key after "banners" can be anything
[desktop.banners.ctrl]
filename = "./banners/desktop/WMDE_FR_2025_Desktop_DE_11/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Desktop_DE_11_ctrl"
tracking = "org-11-251118-ctrl"

[desktop.banners.var]
filename = "./banners/desktop/WMDE_FR_2025_Desktop_DE_11/banner_var.ts"
pagename = "WMDE_FR_2025_Desktop_DE_11_var"
tracking = "org-11-251118-var"

[desktop.test_matrix]
platform = ["edge", "firefox_windows", "chrome_windows", "firefox_linux", "chrome_linux", "chrome_macos", "firefox_macos", "safari" ]
resolution = ["800x600", "1280x720", "1536x864", "1920x1080", "2560x1440"]


[mobile]
name = "Mobile"
icon = "mobile"
campaign = "WMDE_FR_2025_Mobile_DE_09"
description = "based on CTRL of test 8, VAR banner has hightlighted recurring payment intervals"
campaign_tracking = "mob-de-09-ba-251110"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype&useskin=minerva"
preview_link_darkmode = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype&useskin=minerva&minervanightmode=1"
preview_link_offline = ""
preview_url = 'https://de.m.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&useskin=minerva&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_DE"

[mobile.banners.ctrl]
filename = "./banners/mobile/WMDE_FR_2025_Mobile_DE_09/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Mobile_DE_09_ctrl"
tracking = "org-mob09-251110-ctrl"

[mobile.banners.var]
filename = "./banners/mobile/WMDE_FR_2025_Mobile_DE_09/banner_var.ts"
pagename = "WMDE_FR_2025_Mobile_DE_09_var"
tracking = "org-mob09-251110-var"

[mobile.test_matrix]
device = [ "android_old_chrome", "android_new_chrome", "iphone_old", "iphone_small", "iphone_new" ]
orientation = [ "portrait", "landscape"]


[pad]
name = "iPad"
icon = "pad"
campaign = "WMDE_FR_2025_ipad_DE_01"
description = "Based on CTRL of C25_WMDE_iPad_00"
campaign_tracking = "pad01-ba-251027"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype&vectornightmode=1"
preview_link_offline = ""
preview_url = 'https://de.wikipedia.org/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_DE"

[pad.banners.ctrl]
filename = "./banners/pad/WMDE_FR_2025_ipad_DE_01/banner_ctrl.ts"
pagename = "WMDE_FR_2025_ipad_DE_01_ctrl"
tracking = "org-pad01-251027-ctrl"

[pad.banners.var]
filename = "./banners/pad/WMDE_FR_2025_ipad_DE_01/banner_var.ts"
pagename = "WMDE_FR_2025_ipad_DE_01_var"
tracking = "org-pad01-251027-var"

[pad.test_matrix]
device = [ 'ipad_mini', 'ipad_medium', 'ipad_big' ]
orientation = [ "portrait", "landscape"]



[wpde_desktop]
name = "WPDE Desktop"
icon = "desktop"
campaign = "C25_WPDE_Desktop_01"
description = "Based on the VAR of C24_WPDE_Desktop_01; VAR highlights recurrent options in the form"
campaign_tracking = "wpde-01-251027"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_darkmode = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_offline = "/wpde-offline?devbanner={{banner}}"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wpde_desktop.banners.ctrl]
filename = "./banners/wpde_desktop/C25_WPDE_Desktop_01/banner_ctrl.ts"
pagename = "B25_WPDE_Desktop_01_ctrl"
tracking = "wpde-01-251027-ctrl"

[wpde_desktop.banners.var]
filename = "./banners/wpde_desktop/C25_WPDE_Desktop_01/banner_var.ts"
pagename = "B25_WPDE_Desktop_01_var"
tracking = "wpde-01-251027-var"


[wpde_mobile]
name = "WPDE Mobile"
icon = "mobile"
campaign = "C25_WPDE_Mobile_01"
description = "Based on the control banner of last year's mobile-wpde-01"
campaign_tracking = "wpde-mob01-251027"
preview_link = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_darkmode = "/wikipedia.de?devbanner={{banner}}&banner=dev-mode-wpde"
preview_link_offline = "/wpde-offline?devbanner={{banner}}&banner=dev-mode-wpde"
wrapper_template = "wikipedia_de"
wrap_in_wikitext = false
preview_url = 'https://www.wikipedia.de/?banner={{banner}}'

[wpde_mobile.banners.ctrl]
filename = "./banners/wpde_mobile/C25_WPDE_Mobile_01/banner_ctrl.ts"
pagename = "B25_WPDE_Mobile_01_ctrl"
tracking = "wpde-mob01-251027-ctrl"

[wpde_mobile.banners.var]
filename = "./banners/wpde_mobile/C25_WPDE_Mobile_01/banner_var.ts"
pagename = "B25_WPDE_Mobile_01_var"
tracking = "wpde-mob01-251027-var"



[english]
name = "English Desktop"
icon = "desktop"
campaign = "WMDE_FR_2025_Desktop_EN_04"
description = "Based on CTRL desktop-en-03"
campaign_tracking = "en04-ba-251106"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Main_Page?devbanner={{banner}}&banner=B25_WMDE_local_prototype&vectornightmode=1"
preview_link_offline = ""
preview_url = 'https://en.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_EN"

[english.banners.ctrl]
filename = "./banners/english/WMDE_FR_2025_Desktop_EN_04/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Desktop_EN_04_ctrl"
tracking = "org-en04-251106-ctrl"

[english.banners.var]
filename = "./banners/english/WMDE_FR_2025_Desktop_EN_04/banner_var.ts"
pagename = "WMDE_FR_2025_Desktop_EN_04_var"
tracking = "org-en04-251106-var"

[english.test_matrix]
platform = ["edge", "firefox_windows", "chrome_windows", "firefox_linux", "chrome_linux", "chrome_macos", "firefox_macos", "safari" ]
resolution = ["800x600", "1280x720", "1536x864", "1920x1080", "2560x1440"]



[mobile_english]
name = "English Mobile"
icon = "mobile"
campaign = "WMDE_FR_2025_Mobile_EN_01"
description = "Based on VAR of C24_WMDE_Mobile_EN_01"
campaign_tracking = "mob_en01-ba-251027"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Main_Page?devbanner={{banner}}&useskin=minerva&banner=B25_WMDE_local_prototype&minervanightmode=1"
preview_link_offline = ""
preview_url = 'https://en.m.wikipedia.org/wiki/Main_Page?banner={{banner}}&devMode&useskin=minerva'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_EN"

[mobile_english.banners.ctrl]
filename = "./banners/mobile_english/WMDE_FR_2025_Mobile_EN_01/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Mobile_EN_01_ctrl"
tracking = "org-mob_en01-251027-ctrl"

[mobile_english.banners.var]
filename = "./banners/mobile_english/WMDE_FR_2025_Mobile_EN_01/banner_var.ts"
pagename = "WMDE_FR_2025_Mobile_EN_01_var"
tracking = "org-mob_en01-251027-var"

[mobile_english.test_matrix]
device = [ "android_old_chrome", "android_new_chrome", "iphone_old", "iphone_small", "iphone_new" ]
orientation = [ "portrait", "landscape" ]



[fallback]
name = "Fallback Banner"
icon = "desktop"
campaign = "WMDE_FR_2025_Fallback_01"
description = "Based on the fallback banner in the 24 campaign"
campaign_tracking = "fbb01-ba-250225"
preview_link = "/wiki/Main_Page?devbanner={{banner}}&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Main_Page?devbanner={{banner}}&banner=B25_WMDE_local_prototype&vectornightmode=1"
preview_link_offline = ""
preview_url = 'https://de.wikipedia.org/wiki/Hamster?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_EN"

[fallback.banners.ctrl]
filename = "./banners/fallback/WMDE_FR_2025_Fallback_01/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Fallback_01_ctrl"
tracking = "org-fbb01-250225-ctrl"

[fallback.banners.var]
filename = "./banners/fallback/WMDE_FR_2025_Fallback_01/banner_ctrl.ts"
pagename = "WMDE_FR_2025_Fallback_01_var"
tracking = "org-fbb01-250225-ctrl"

[fallback.test_matrix]
platform = ["edge", "firefox_windows", "chrome_windows", "firefox_linux", "chrome_linux", "chrome_macos", "firefox_macos", "safari" ]
resolution = ["800x600", "1280x720", "1536x864", "1920x1080", "2560x1440"]

[cheering_feature]
name = "Cheering Feature"
icon = "desktop"
campaign = "cheering_00"
description = "Feature banner for the cheering element"
campaign_tracking = "cheering00-ba-240725"
preview_link = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype"
preview_link_darkmode = "/wiki/Wikipedia:Hauptseite?devbanner={{banner}}&banner=B25_WMDE_local_prototype&vectornightmode=1"
preview_link_offline = ""
preview_url = '/wiki/Wikipedia:Hauptseite?banner={{banner}}&devMode'
wrapper_template = "wikipedia_org"
use_of_funds_source = "MediaWiki:WMDE_Fundraising/UseOfFunds_2025_EN"

[cheering_feature.banners.ctrl]
filename = "./banners/features/cheering_00/banner_ctrl.ts"
pagename = "B25_WMDE_Cheering_00_ctrl"
tracking = "org-cheering00-240725-ctrl"

[cheering_feature.banners.var]
filename = "./banners/features/cheering_00/banner_ctrl.ts"
pagename = "B25_WMDE_Cheering_00_var"
tracking = "org-cheering00-240725-var"

[cheering_feature.test_matrix]
platform = ["edge", "firefox_windows", "chrome_windows", "firefox_linux", "chrome_linux", "chrome_macos", "firefox_macos", "safari" ]
resolution = ["800x600", "1280x720", "1536x864", "1920x1080", "2560x1440"]
